# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170518_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='num_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='num_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
