# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170518_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orderitem', through='myapp.OrderItem', to='myapp.FoodItem'),
        ),
    ]
